### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Poussinou** [jonathansautter/AutoOff#4]
Hi,

Since this app is MIT licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind, and we already have a Request For Packaging [here](https://gitlab.com/fdroid/rfp/issues/267), we just need you tag your releases.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you (we're busy at F-Droid, it can take a lot of time)?

**Comment by therealmaxmoon** [comment]
I want this app in the F-Droid store, too. Would be very nice if Jonathan could do the needed stuff to release it there.

Pleeeeeease, Jonathan *freundlichKuck*

**Comment by Rudloff** [comment]
Hello,
I confirm we could package the app for you, but we would need:
* Your approval
* [Git tags](https://github.com/jonathansautter/AutoOff/tags) for stable releases
